### ISSUE TITLE
Installation prerequisites

### ISSUE THREAD

**Issue by EduardoMejiaL** [Stanislav-Lapata/lapce-angular#1]
Hi, this is kind of obvious but I struggle a while trying to use the plugin because I got confused between `@angular/language-service` and `@angular/language-server`, I can now use it but I had to install both globally

It would be nice if the `README` contains this information, If you agree I can make a pull request with those changes to your `README`.

**Comment by Stanislav-Lapata** [comment]
Sorry for long response. I have used this [instruction](https://github.com/neovim/nvim-lspconfig/blob/v0.1.5/doc/server_configurations.md#angularls) because I use neovim for daily tasks 
```bash 
npm install -g @angular/language-server
```

I think you are right, we need to add simple information
